config/routes.rb
ClientelaMysql::Application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'invitations' }

  match '/dashboard', :to => redirect("/")
  root :to => "dashboard#show"
  resources :menus, :only => [:create, :destroy]
  resource :welcome, :only => [:show, :update], :controller => :welcome
  resources :users, :except => [:new, :create, :show] do
    put :update_authentication_token, :on => :member
    put :survey, :on => :collection
  end

  resources :contacts do
    get :autocomplete_contact_name, :on => :collection
    get :autocomplete_contact_title, :on => :collection
    get :autocomplete_company_name, :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :tags, :only => [:index, :show] do
    resources :contacts, :only => [:index]
  end
  resources :notes, :only => [:create, :edit, :update, :destroy]
  resources :tasks, :except => [:show] do
    get 'completed', :on => :collection
    put 'complete', :on => :member
  end
  resources :facts do
    get 'closed', :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :deals do
    collection do
      get :prospect, :qualify, :proposal, :negotiation, :lost, :won
    end
    resource :subscription, :only => [:create, :destroy]
  end
  resources :companies, :only => [:edit, :update, :show] do
    resource :subscription, :only => [:create, :destroy]
  end
  resources :contact_imports do
    post 'revert', :on => :member
  end
  resources :relationships, :only => [:create, :destroy]
  resource :search, :only => [:show]

  resources :task_categories, :except => [:index, :show, :destroy]
  resources :groups, :except => [:show]

  if Rails.env.production?
    match '/campaigns' => "dashboard#soon", :as => :campaigns
  else
    resources :campaigns
  end

  match '/reports' => "reports#index"
  match '/surveys' => "dashboard#soon", :as => :surveys
  match '/support/api' => "support#api"
  match '/hooks/wufoo' => "hooks#wufoo", :via => :post
  

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :user_ids, :individual
  has_and_belongs_to_many :users
  has_many :permissions, :dependent => :destroy
  validates :name, :presence => true
  scope :individual, where(:individual => true)
  scope :not_individual, where(:individual => false)
end

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
  respond_to :html, :xml, :json
  actions :new, :edit, :destroy, :index, :create, :update
  before_filter :fix_params, :only => [:update]

  private
  def fix_params
    params[:group] && (params[:group][:user_ids] ||= [])
  end
  def collection
    @groups ||= end_of_association_chain.not_individual
  end
end

app/views/groups/_form.html.erb
<%= form_for @group, :builder => Clientela::FormBuilder do |f| %>
  <div class="attributes">
    <%= f.text_field_with_label :name, :wrapper_class => "highlight" %>

    <%= label_tag "Quais são os usários desse grupo?" %>
    <br/>
    <br/>
    <%- User.active.each do |user| -%>
      <div>
        <%= check_box_tag "group[user_ids][]", user.id, @group.users.include?(user), :id => "group_user_ids_#{user.id}" %>
        <%= label_tag "group_user_ids_#{user.id}", user.name %>
      </div>
    <%- end -%>

    <%= spinner_submit_with_cancel(f) %>
  </div>
<%- end -%>

app/views/groups/_group.html.erb
<li>
  <%= small_thumb_tag('iconika-grey-icons/48x48/comment.png') %>
  <div class="fact-data">
    <div class="fact-name"><%= link_to group.name, edit_group_url(group) %></div>
    <div class="fact-last-update">
      <%= group.users.map(&:name).sort.join(", ") %>
    </div>
  </div>
</li>

app/views/groups/_welcome.pt_BR.html.erb
<div class="welcome">
  <div class="welcome-bar">
    <h1>Gerencie permissões de acesso usando grupos</h1>
    <p>Grupos são úteis quando você deseja que somente algumas pessoas vejam um determinado contato, nota ou oportunidade.</p>
    <br/>
    <p>Você pode, por exemplo, criar um grupo para cada uma das suas equipes de venda. Ou criar um grupo para o departamento de marketing e outro para o departamento de vendas. As possibilidades são muitas!</p>
  </div>

  <div class="middle-bar">
    <h1>Grupo</h1>
    <p>Certo número de pessoas reunidas. Fonte: <%= link_to "Michaelis", "http://michaelis.uol.com.br/moderno/portugues/index.php?lingua=portugues-portugues&palavra=grupo" %>.</p>
  </div>
</div>

app/views/groups/edit.html.erb
<%= content_box(:span => link_to_destroy(@group)) do -%>
  <%= render 'form' %>
<%- end -%>

app/views/groups/index.html.erb
<%- sidebar_box do -%>
  <%= sidebar_module_box :header => 'actions' do %>
    <%= link_to content_tag(:span, t(".add_new")), new_group_url, :class => :button %>
  <%- end -%>
<%- end -%>

<%= content_box do -%>
  <%- if @groups.any? -%>
    <div class="group-index-list index-list">
      <ul>
        <%= render @groups %>
      </ul>
    </div>
  <%- else -%>
    <%= render :partial => "welcome" %>
  <%- end -%>
<%- end -%>

app/views/groups/new.html.erb
<%= content_box do -%>
  <%= render 'form' %>
<%- end -%>