config/routes.rb
ClientelaMysql::Application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'invitations' }

  match '/dashboard', :to => redirect("/")
  root :to => "dashboard#show"
  resources :menus, :only => [:create, :destroy]
  resource :welcome, :only => [:show, :update], :controller => :welcome
  resources :users, :except => [:new, :create, :show] do
    put :update_authentication_token, :on => :member
    put :survey, :on => :collection
  end

  resources :contacts do
    get :autocomplete_contact_name, :on => :collection
    get :autocomplete_contact_title, :on => :collection
    get :autocomplete_company_name, :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :tags, :only => [:index, :show] do
    resources :contacts, :only => [:index]
  end
  resources :notes, :only => [:create, :edit, :update, :destroy]
  resources :tasks, :except => [:show] do
    get 'completed', :on => :collection
    put 'complete', :on => :member
  end
  resources :facts do
    get 'closed', :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :deals do
    collection do
      get :prospect, :qualify, :proposal, :negotiation, :lost, :won
    end
    resource :subscription, :only => [:create, :destroy]
  end
  resources :companies, :only => [:edit, :update, :show] do
    resource :subscription, :only => [:create, :destroy]
  end
  resources :contact_imports do
    post 'revert', :on => :member
  end
  resources :relationships, :only => [:create, :destroy]
  resource :search, :only => [:show]

  resources :task_categories, :except => [:index, :show, :destroy]
  resources :groups, :except => [:show]

  if Rails.env.production?
    match '/campaigns' => "dashboard#soon", :as => :campaigns
  else
    resources :campaigns
  end

  match '/reports' => "reports#index"
  match '/surveys' => "dashboard#soon", :as => :surveys
  match '/support/api' => "support#api"
  match '/hooks/wufoo' => "hooks#wufoo", :via => :post
  

  

end

app/models/company.rb
class Company < Entity
  attr_accessible :name, :photo, :delete_photo, :tag_list, :addresses_attributes, :emails_attributes, :phones_attributes, :websites_attributes, :permissions_attributes
  has_many :contacts
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  respond_to :html, :xml, :json
  actions :edit, :show, :update

  def update
    update! { params[:referer] || @company }
  end
end

app/views/companies/_contacts_sidebar.html.erb
<%= sidebar_module_box(:header => :header) do -%>
  <ul class="contacts-list">
    <%= render :partial => "contacts/contact", :collection => resource.contacts -%>
  </ul>
  <br style="clear: both;"/>
<%- end -%>

app/views/companies/_form.html.erb
<%- with_avatar = (resource.new_record? ? "" : "with-avatar") -%>

<%= form_for resource, :builder => Clientela::FormBuilder, :html => { :multipart => true } do |f| %>
  <%= hidden_field_tag :referer, request.referer %>

  <div class="attributes <%= with_avatar %>">
  
    <%= render :partial => "entities/avatar", :locals => {:resource=>resource} -%>

    <%= f.text_field_with_label :name, :wrapper_class => "highlight" %>
    <%= nested_attribute(f, :phones) %>
    <%= nested_attribute(f, :emails) %>
    <%= nested_attribute(f, :websites) %>
    <%= nested_attribute(f, :addresses) %>    
    <%= f.text_field_with_label :tag_list %>
    
    <div class="sample-tags">
      <%- most_used_tags.each do |tag| -%>
        <span><%= tag %></span>
      <%- end -%>
      <p><%= t("entities.form.sample_tags_html")%></p>
    </div>
    
    <%= spinner_submit_with_cancel(f) %>
  </div>
<%- end -%>

<script type="text/javascript">
  <%= %{var tags = [#{ActsAsTaggableOn::Tag.all.map { |t| %{["#{t}","#{t}"]} }.join(',')}];}.html_safe %>
</script>

app/views/companies/_form_avatar.html.erb
<%= form_for resource, :html => { :multipart => true, :id => dom_id(resource, :avatar_edit), :style => "display: none", :class => "avatar_edit" } do |f| %>
  <div class="attributes">
    <div class="attribute highlight">
      <div class="label">
        <%= image_tag resource.small_avatar %>
      </div>
      <div class="field">
        <%= t(".change", :name => resource.name) %>
        <%- if resource.photo.exists? -%>
          <br/>
          <%= link_to t(".delete"), company_url(resource, :contact => {:delete_photo => 1}), :method => :put %>
        <%- end -%>
      </div>
      <br style="clear: both;"/>
    </div>
    <div class="attribute highlight">
      <div class="label">
        <%= t(".select") %>
      </div>
      <div class="field">
        <%= f.file_field :photo %>
      </div>
    </div>
    <div class="actions">
      <%= spinner_submit(f) %>
      <%= t("common.or") %>
      <%= link_to t("common.cancel"), '#', :class => 'cancel' %>
    </div>
  </div>
<%- end -%>

app/views/companies/edit.html.erb
<%= content_box do -%>
  <%= render 'form' %>
  <%= render 'form_avatar' %>
  
  <script type="text/javascript">
    $(document).ready(function() {
      var contact_dom_id = '<%= dom_id(resource) %>';
      $("div#avatar a").click(function(){
        $("#edit_" + contact_dom_id).hide();
        $("#avatar_edit_" + contact_dom_id).show();
        return false;
      });

      $(".avatar_edit a.cancel").click(function(){
        $("#edit_" + contact_dom_id).show();
        $("#avatar_edit_" + contact_dom_id).hide();
        return false;
      });
    });
  </script>
<%- end -%>

app/views/companies/show.html.erb
<%= sidebar_box do -%>
  <%= render :partial => "entities/contact_data" %>
  <%= render :partial => "contacts_sidebar" %>
  <%= render_tag_list @company.tags.grouped_by_initial %>
  <%= render :partial => "shared/subscriptions" %>
  <%= render :partial => "shared/dropbox" %>
<%- end -%>

<%= content_box do -%>
  <%= inner_header do -%>
    <h1 style="display: inline;"><%= resource.name %></h1>
    <span style="float: right; font-size: 0.9em;"><%= link_to content_tag(:span, t("common.edit")), edit_company_url %></span>
  <%- end -%>

  <%= render :partial => "notes/list" %>
<%- end -%>