config/routes.rb
ClientelaMysql::Application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'invitations' }

  match '/dashboard', :to => redirect("/")
  root :to => "dashboard#show"
  resources :menus, :only => [:create, :destroy]
  resource :welcome, :only => [:show, :update], :controller => :welcome
  resources :users, :except => [:new, :create, :show] do
    put :update_authentication_token, :on => :member
    put :survey, :on => :collection
  end

  resources :contacts do
    get :autocomplete_contact_name, :on => :collection
    get :autocomplete_contact_title, :on => :collection
    get :autocomplete_company_name, :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :tags, :only => [:index, :show] do
    resources :contacts, :only => [:index]
  end
  resources :notes, :only => [:create, :edit, :update, :destroy]
  resources :tasks, :except => [:show] do
    get 'completed', :on => :collection
    put 'complete', :on => :member
  end
  resources :facts do
    get 'closed', :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :deals do
    collection do
      get :prospect, :qualify, :proposal, :negotiation, :lost, :won
    end
    resource :subscription, :only => [:create, :destroy]
  end
  resources :companies, :only => [:edit, :update, :show] do
    resource :subscription, :only => [:create, :destroy]
  end
  resources :contact_imports do
    post 'revert', :on => :member
  end
  resources :relationships, :only => [:create, :destroy]
  resource :search, :only => [:show]

  resources :task_categories, :except => [:index, :show, :destroy]
  resources :groups, :except => [:show]

  if Rails.env.production?
    match '/campaigns' => "dashboard#soon", :as => :campaigns
  else
    resources :campaigns
  end

  match '/reports' => "reports#index"
  match '/surveys' => "dashboard#soon", :as => :surveys
  match '/support/api' => "support#api"
  match '/hooks/wufoo' => "hooks#wufoo", :via => :post
  

  

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  VALUE_TYPES = %w(fixed hourly monthly yearly)
  STATUSES = %w(prospect qualify proposal negotiation lost won)
  attr_accessible :name, :description, :contact, :value, :value_type, :status, :duration, :contact_id, :tag_list, :assigned_to_id, :assigned_to, :probability, :contact_name, :permissions_attributes

  has_many :activities, :as => :activitable
  has_many :permissions, :as => :referred, :dependent => :destroy
  has_many :groups, :through => :permissions
  has_many :notes, :as => :notable, :dependent => :destroy
  has_many :tasks, :as => :taskable, :dependent => :destroy
  has_many :relationships, :dependent => :destroy, :as => :entity
  has_many :contacts, :through => :relationships
  has_many :subscriptions, :as => :subject, :dependent => :destroy
  has_many :subscribers, :through => :subscriptions, :class_name => "User"
  belongs_to :assigned_to, :class_name => "User"

  accepts_nested_attributes_for :permissions, :allow_destroy => true, :reject_if => proc { |attributes| attributes['group_id'].blank? }

  validates :name, :value, :assigned_to, :presence => true
  validates :status, :inclusion => { :in => STATUSES }
  validates :value_type, :inclusion => { :in => VALUE_TYPES }, :allow_nil => true
  validates :probability, :inclusion => { :in => 0..100 }

  scope :pending, :conditions => ["status NOT IN ('won','lost')"], :extend => DealTotalExtension
  STATUSES.each do |status|
    scope status.to_sym, :conditions => {:status => status}, :extend => DealTotalExtension
  end

  scope :created_between, lambda { |from,to| where("created_at BETWEEN ? AND ?", from.beginning_of_day,to.end_of_day) }
  scope :won_between, lambda { |from,to| won.where("status_last_change_at BETWEEN ? AND ?", from.beginning_of_day,to.end_of_day) }

  before_save :update_status_last_change_at, :update_probability
  before_create :set_permissions_to_contact

  acts_as_taggable_with_grouped_by_initial

  define_index do
    indexes name, description
  end

  def total_value
    if self.value_type == 'fixed'
      self.value
    else
      self.value * self.duration
    end
  end

  def contact_name
    @contact_name
  end

  def contact_name=(name)
    return name if name.blank?
    @contact_name = name

    unless contact = Contact.find_by_name(name)
      contact = Contact.create(:name => name)
      @set_permissions_to_contact = contact
    end
    contacts << contact
  end

  def set_permissions_to_contact
    return unless @set_permissions_to_contact
    self.permissions.each do |permission|
      @set_permissions_to_contact.permissions.create!(:group => permission.group)
    end
  end

  class << self
    def value_types
      VALUE_TYPES
    end

    def statuses
      STATUSES
    end

    def quantitative_data(year, goal)
      data = []
      (1..12).each do |month|
        from_date   = Date.new(year, month, 1)
        to_date     = Date.new(year, month, -1)
        data << [abbr_i18n(to_date, :abbr_month)].concat(calculate_quantitative_by_date(from_date,to_date)).concat([goal])
      end
      concat_with_goal(data, goal)
    end

    def qualitative_data(year, goal)
      data = []
      (1..12).each do |month|
        from_date   = Date.new(year, month, 1)
        to_date     = Date.new(year, month, -1)
        data << [abbr_i18n(to_date, :abbr_month)].concat(calculate_qualitavide_by_date(from_date,to_date)).concat([goal])
      end
      concat_with_goal(data, goal)
    end

    def report_values
      [:week, :month, :year]
    end

    private
    def concat_with_goal(data, goal)
      [["",0,0,goal]].concat(data).concat([["",0,0,goal]])
    end

    def calculate_quantitative_by_date(from,to)
  		wons  = Deal.won_between(from,to).count
  		all   = Deal.created_between(from,to).count
  		[all, wons]
    end

    def calculate_qualitavide_by_date(from,to)
      wons  = Deal.won_between(from,to).map(&:total_value).reduce(0,:+)
      all   = Deal.created_between(from,to).map(&:total_value).reduce(0,:+)
      [all, wons]
    end

    def abbr_i18n(date, format)
      I18n.l(date, :format => format)
    end
  end

  private
  def update_status_last_change_at
    self.status_last_change_at = Time.now if status_changed? || status_last_change_at.blank?
  end

  def update_probability
    self.probability = 100 if status == 'won'
    self.probability = 0 if status == 'lost'
  end
end

app/controllers/deals_controller.rb
class DealsController < InheritedResources::Base
  respond_to :html, :xml, :json
  respond_to :js, :only => [:update]
  load_and_authorize_resource :except => [:new, :index, :create]

  def index
    @pendings = Deal.accessible_by(current_ability).pending.uniq
    @wons = Deal.accessible_by(current_ability).won.uniq
    @losts = Deal.accessible_by(current_ability).lost.uniq
  end
  def prospect
    @deals = Deal.accessible_by(current_ability).prospect.uniq
    render 'index'
  end
  def qualify
    @deals = Deal.accessible_by(current_ability).qualify.uniq
    render 'index'
  end
  def proposal
    @deals = Deal.accessible_by(current_ability).proposal.uniq
    render 'index'
  end
  def negotiation
    @deals = Deal.accessible_by(current_ability).negotiation.uniq
    render 'index'
  end
  def won
    @deals = Deal.accessible_by(current_ability).won.uniq
    render 'index'
  end
  def lost
    @deals = Deal.accessible_by(current_ability).lost.uniq
    render 'index'
  end
end

app/helpers/deals_helper.rb
module DealsHelper
  def checked(deal, status)
    return "checked" if deal.status.to_sym == status.to_sym
  end

  def formated_bid(deal)
    return if !(!deal.value.blank? && deal.value_type) || deal.value.zero?
    content_tag(:p, t("deals.common.#{deal.value_type}_bid", :value => number_to_currency(deal.value), :duration => deal.duration, :total => number_to_currency(deal.value*deal.duration.to_i)))
  end
end

app/views/deals/_deal.html.erb
<li>
  <%= small_thumb_tag('iconika-grey-icons/48x48/star.png') %>
  <div class="deal-data">
    <div class="deal-name"><%= link_to deal.name, deal %></div>
    <div class="deal-bid">
      <%= formated_bid(deal) %>
    </div>
  </div>
</li>

app/views/deals/_form.html.erb
<%
(Group.individual.all + current_user.groups).uniq.each do |group|
  @deal.permissions.build(:group => group) unless @deal.groups.include?(group)
end
%>

<%= form_for(@deal, :builder => Clientela::FormBuilder) do |f| %>
  <div class="attributes">
    <%= f.text_field_with_label :name, :wrapper_class => "highlight" %>

    <%= f.text_area_with_label :description %>

    <div class="attribute">
      <div class="label">
        <%= f.label :value %>
      </div>
      <div class="field">
        <%= f.text_field :value, :size => 8 %>
        <%= f.select :value_type, options_with_translation(Deal.value_types) %>
        <span id='duration'>
          <%= t('.for') %>
          <%= f.text_field :duration, :size => 2, :style => "float: none;" %>
          <span id="hourly" class="duration_span"><%= t(".hours") %></span>
          <span id="monthly" class="duration_span"><%= t(".months") %></span>
          <span id="yearly" class="duration_span"><%= t(".years") %></span>
        </span>
      </div>
    </div>

    <%= f.select_field_with_label(:assigned_to_id, users_for_assign) %>

    <%- if resource.new_record? -%>
      <%= f.autocomplete_field_with_label :contact_name, :url => autocomplete_contact_name_contacts_path %>
    <%- end -%>

    <%= render "shared/permissions", :f => f, :resource => @deal %>

    <%= f.text_field_with_label :tag_list %>
    <div class="sample-tags">
      <%- most_used_tags.each do |tag| -%>
        <span><%= tag %></span>
      <%- end -%>
      <p><%= t("entities.form.sample_tags_html")%></p>
    </div>

    <%= spinner_submit_with_cancel(f) %>
  </div>
<% end %>

<script type="text/javascript">
  <%= %{var tags = [#{ActsAsTaggableOn::Tag.all.map { |t| %{["#{t}","#{t}"]} }.join(',')}];}.html_safe %>
</script>

app/views/deals/_list.html.erb
<%- if deals.any? -%>
  <h3 class=<%= "#{message}" %>>
    <%= t(".#{message}") %>
    <span style="float: right; font-weight: normal;"><%= t(".total", :count => deals.size, :value => number_to_currency(deals.map(&:total_value).sum)) %></span>
  </h3>

  <div class="deals-index-list index-list">
    <ul>
      <%= render deals %>
    </ul>
  </div>
  <br style="clear: both;"><br/>
<%- end -%>

app/views/deals/_pending_list.html.erb
<li>
  <span class="created-at"><%= l(deal.created_at, :format => :activity) %></span>
  <h3><%= link_to deal.name, deal_path(deal) -%></h3>
  <%= formated_bid(deal) -%>
</li>

app/views/deals/_sidebar_list.html.erb
<div id="deals-container">
  <%- if deals.any? -%>
    <%= sidebar_module_box(:header => :header) do -%>
      <%= render :partial => "deals/pending_list", :collection => deals, :as => :deal -%>
    <%- end -%>
  <%- end -%>
</div>

app/views/deals/_welcome.pt_BR.html.erb
<div class="welcome">
  <div class="welcome-bar">
    <h1>Oportunidades são a chave do seu negócio</h1>
    <p>Você poderá organizar e atualizar todas as suas oportunidades. Mantenha notas e tarefas relacionadas as oportunidades, além de informações importantes para o seu sucesso.</p>
  </div>

  <div class="middle-bar">
    <h1>Oportunidade</h1>
    <p>Ocasião favorável. Fonte: <%= link_to "Michaelis", "http://michaelis.uol.com.br/moderno/portugues/index.php?lingua=portugues-portugues&palavra=oportunidade" %>.</p>
  </div>
</div>

app/views/deals/edit.html.erb
<%= content_box do -%>
  <%= inner_header do -%>
    <span style="float: right; font-size: 0.9em;"><%= link_to_destroy(@deal) %></span>
    <h1><%= t(".header", :name => @deal.name) %></h1>
  <%- end -%>

  <%= render 'form' %>
<%- end -%>

app/views/deals/index.html.erb
<%= sidebar_box do -%>
  <%= sidebar_module_box :header => 'actions' do %>
    <%= link_to content_tag(:span, t(".add_new_deal")), new_deal_path, :class => "button" %>
  <%- end -%>
  <%= sidebar_module_box :header => 'filters' do %>
    <%= link_to "Prospect", prospect_deals_url %>
    <br/>
    <%= link_to "Qualificação", qualify_deals_url %>
    <br/>
    <%= link_to "Proposta", proposal_deals_url %>
    <br/>
    <%= link_to "Negociação", negotiation_deals_url %>
    <br/>
    <%= link_to "Perdido", lost_deals_url %>
    <br/>
    <%= link_to "Ganho", won_deals_url %>
  <%- end -%>
  <%= render_tag_list Deal.tags_grouped_by_initial %>
<%- end -%>

<%= content_box do -%>
  <% if @deals %>
    <%= render :partial => "deals/list", :locals => { :deals => @deals, :message => action_name } %>
  <% elsif @pendings.any? or @wons.any? or @losts.any? %>
    <%= render :partial => "deals/list", :locals => { :deals => @pendings, :message => :pending } %>
    <%= render :partial => "deals/list", :locals => { :deals => @wons, :message => :won } %>
    <%= render :partial => "deals/list", :locals => { :deals => @losts, :message => :lost } %>
  <% else %>
    <%= render :partial => "welcome"%>
  <% end %>
<%- end -%>

app/views/deals/new.html.erb
<%= content_box do -%>
  <%= render 'form' %>
<%- end -%>

app/views/deals/show.html.erb
<%= sidebar_box do -%>
  <%= render :partial => "tasks/sidebar_list" %>

  <%= sidebar_module_box(:header => :sidebar_header_status) do -%>
    <%= form_for(@deal, :remote => true) do |f| %>
      <fieldset class="deal-status">
        <%- Deal.statuses.each do |status| -%>
          <label class="<%= status %> <%= checked(@deal, status) %>" for="deal_status_<%= status %>"><%= f.radio_button(:status, status, :class => 'submit-on-change') + " " + t(".statuses.#{status}") %></label>
        <%- end -%>
      </fieldset>
    <%- end -%>
    <br/>
    <h2><%= t(".sidebar_header_probability") %></h2>
    <br/>
    <div id="probability-slider" style="margin-right: 50px;">&nbsp;</div>
    <div id="amount" style="float: right; margin-top: -15px;">&nbsp;</div>
    <br/>
    <%= javascript_tag %{
      $(function() {
        $("#probability-slider").slider({
          value:#{resource.probability},
          min: 0,
          max: 100,
          step: 5,
          slide: function(event, ui) {
            $("#amount").html(ui.value + "%");
          },
          change: function( event, ui ) {
            if(event.originalEvent == undefined)
              return;
            $.ajax({
              type: 'PUT',
              url: "#{deal_url(resource)}",
              dataType: "script",
              data: {
                deal: {
                  probability: ui.value
                }
              }
            });
          }
        });
        $("#amount").html($("#probability-slider").slider("value") + "%");
      });
    } %>
  <%- end -%>
  <%= sidebar_module_box(:header => :description) do -%>
    <%= simple_format(@deal.description) %>
  <%- end -%>
  <%= render :partial => "notes/sidebar_list" %>
  <%= render :partial => "relationships/sidebar_list" %>

  <%= render_tag_list @deal.tags.grouped_by_initial %>
  <%= render :partial => "shared/subscriptions" %>
<%- end -%>

<%= content_box do -%>
  <%= inner_header do -%>
    <span style="float: right; font-size: 0.9em;"><%= link_to t("common.edit"), edit_deal_url%></span>
    <h1><%= @deal.name %></h1>
    <%= formated_bid(@deal) %>
  <%- end -%>

  <div style="clear:both;"></div>
  <%= render :partial => "notes/list" %>
<%- end -%>