config/routes.rb
ClientelaMysql::Application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'invitations' }

  match '/dashboard', :to => redirect("/")
  root :to => "dashboard#show"
  resources :menus, :only => [:create, :destroy]
  resource :welcome, :only => [:show, :update], :controller => :welcome
  resources :users, :except => [:new, :create, :show] do
    put :update_authentication_token, :on => :member
    put :survey, :on => :collection
  end

  resources :contacts do
    get :autocomplete_contact_name, :on => :collection
    get :autocomplete_contact_title, :on => :collection
    get :autocomplete_company_name, :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :tags, :only => [:index, :show] do
    resources :contacts, :only => [:index]
  end
  resources :notes, :only => [:create, :edit, :update, :destroy]
  resources :tasks, :except => [:show] do
    get 'completed', :on => :collection
    put 'complete', :on => :member
  end
  resources :facts do
    get 'closed', :on => :collection
    resource :subscription, :only => [:create, :destroy]
  end
  resources :deals do
    collection do
      get :prospect, :qualify, :proposal, :negotiation, :lost, :won
    end
    resource :subscription, :only => [:create, :destroy]
  end
  resources :companies, :only => [:edit, :update, :show] do
    resource :subscription, :only => [:create, :destroy]
  end
  resources :contact_imports do
    post 'revert', :on => :member
  end
  resources :relationships, :only => [:create, :destroy]
  resource :search, :only => [:show]

  resources :task_categories, :except => [:index, :show, :destroy]
  resources :groups, :except => [:show]

  if Rails.env.production?
    match '/campaigns' => "dashboard#soon", :as => :campaigns
  else
    resources :campaigns
  end

  match '/reports' => "reports#index"
  match '/surveys' => "dashboard#soon", :as => :surveys
  match '/support/api' => "support#api"
  match '/hooks/wufoo' => "hooks#wufoo", :via => :post
  

  

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    tags = ActsAsTaggableOn::Tag.joins(:taggings).all.uniq.group_by {|t| t.name.chars.first}.sort
    @first_half = tags[0..((tags.size.to_f/2).ceil) - 1]
    @second_half = tags[((tags.size.to_f/2).ceil)..-1]
  end
  
  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @contacts = Contact.tagged_with(@tag)
    @deals = Deal.tagged_with(@tag)
    @companies = Company.tagged_with(@tag)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def most_used_tags
    result = ["Cliente", "Fornecedor", "Prospect", "Lead", "Aluno", "Tutor", "Vip", "Rio de Janeiro"]
    result.insert(0,Contact.tag_counts_on(:tags).map(&:name)).flatten!
    result[0,8]
  end
end

app/views/tags/_sidebar_list.html.erb
<%- unless tags.blank? -%>
  <div class="sidebar-module">
    <h2><%= t('.header') %></h2>
    <div class="inner">
      <%- tags.each do |value| -%>
        <p style="line-height: 1.8em;">
          <strong><%= value.first.capitalize %></strong>
          <%- value.last.each do |tag| -%>
            <% url = controller_name == "contacts" ? tag_contacts_url(tag) : tag_url(tag) %>
            <%= link_to tag.name, url %>
          <%- end -%>
        </p>
      <%- end -%>
    </div>
  </div>
<%- end -%>

app/views/tags/_welcome.pt_BR.html.erb
<div class="welcome-bar">
  <h1>Seus dados categorizados</h1>
  <p>Utilize para categorizar seus Contatos e Oportunidades.</p>
</div>

<div class="middle-bar">
  <h1>Categorias</h1>

  <p>São uma ótima forma de você organizar seus dados. Você pode marcar um contato como <strong>cliente</strong> ou <strong>fornecedor</strong> e rapidamente visualizar todos os seus dados categorizados.</p>
</div>

app/views/tags/index.html.erb
<%= content_box do -%>
  <% if @first_half.any? %>
  <table id="tags-table">
    <tr>
      <td>
        <% @first_half.each do |value| %>
          <%= value.first.capitalize %>
          <% value.last.each do |tag| %>
            <%= link_to tag.name, tag_url(tag) %>
          <% end %>
          <br />
        <% end %>
      </td>
      <td>
        <% @second_half.each do |value| %>
          <%= value.first.capitalize %>
          <% value.last.each do |tag| %>
            <%= link_to tag.name, tag_url(tag) %>
          <% end %>
          <br />
        <% end %>
      </td>
    </tr>
  </table>
<% else %>
  <%= render :partial => "welcome"%>
<% end %>
<%- end -%>

app/views/tags/show.html.erb
<%= content_box do -%>
  <%= inner_header do -%>
    <h2><%= "#{t(".header")} '#{@tag}'" %></h2>
  <%- end -%>
  <%  unless @contacts.blank? %>
    <h3><%= t(".contacts") %></h3>
    <div class="index-list">
      <ul>
        <%= render :partial => "contacts/contact", :collection => @contacts %>
      </ul>
    </div>
    <br style="clear: both;"/><br/>
  <% end %>


  <%  unless @deals.blank? %>
    <h3><%= t(".deals") %></h3>
    <div class="index-list">
      <ul>
        <%= render :partial => "deals/deal", :collection => @deals %>
      </ul>
    </div>
    <br style="clear: both;"><br/>
  <% end %>
  <%  unless @companies.blank? %>
    <h3><%= t(".companies") %></h3>
    <div class="index-list">
      <ul>
      <% @companies.each do |company| %>
        <li>
          <div class="avatar">
            <%= image_tag "iconika-grey-icons/48x48/home.png" %>
          </div>
          <div class="contact-data">
            <div class="contact-name">
              <%= link_to company.name, company %>
            </div>
            <%- unless company.emails.blank? -%>
              <div class="contact-email"><%= company.emails.first.address %></div>
            <%- end -%>
          </div>
      <% end %>
      </ul>
    </div>
    <br style="clear: both;"><br/>
    <% end %>
<%- end -%>